/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-wizard.component';
const styles_NgxWizardComponent:any[] = ([] as any[]);
export const RenderType_NgxWizardComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NgxWizardComponent,data:{}});
export function View_NgxWizardComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['I AM THE TAB WIZARD'])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(null as any),(null as any));
}
export function View_NgxWizardComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngx-wizard',([] as any[]),
      (null as any),(null as any),(null as any),View_NgxWizardComponent_0,RenderType_NgxWizardComponent)),
      i0.ɵdid(49152,(null as any),0,i1.NgxWizardComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const NgxWizardComponentNgFactory:i0.ComponentFactory<i1.NgxWizardComponent> = i0.ɵccf('ngx-wizard',
    i1.NgxWizardComponent,View_NgxWizardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovRGV2ZWxvcG1lbnQvbmd4LXdpemFyZC9zcmMvbmd4LXdpemFyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovRGV2ZWxvcG1lbnQvbmd4LXdpemFyZC9zcmMvbmd4LXdpemFyZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9EZXZlbG9wbWVudC9uZ3gtd2l6YXJkL3NyYy9uZ3gtd2l6YXJkLmNvbXBvbmVudC50cy5OZ3hXaXphcmRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L0RldmVsb3BtZW50L25neC13aXphcmQvc3JjL25neC13aXphcmQuY29tcG9uZW50LnRzLk5neFdpemFyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8aDE+SSBBTSBUSEUgVEFCIFdJWkFSRDwvaDE+XG4gICAgIiwiPG5neC13aXphcmQ+PC9uZ3gtd2l6YXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7TUFBQSw0Q0FBSTtNQUF3Qjs7O29CQ0RwQztNQUFBO2FBQUE7VUFBQTs7OyJ9
